name: Horizon Infinity
favicon: null
layout_spectrum: 0.74785
typography_spectrum: 0.48744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#35373a'
    - '#212224'
    - '#484848'
    - '#5a5a5a'
  brandStrength: 0.09835425089113414
  lightness: 0.17915336298756301
  saturation: 0.8885049582459033
  rhythmicContrast: 0.7769101753365248
purpose: []
